### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by matthias-christen**
Added support for Windows (creating memory mapped file and mutex (for synchronization) in binding.cc; locking using mutex in memcache.cc).

### CODE REVIEW

**Comment by kyriosli** [comment]
Thank you very much! Since I know little about ms developing, I am not sure about the build process and the test cases totally. But it seems worth a try!

**Comment by matthias-christen** [comment]
Thank you for accepting the pull request!

Building on Windows is just like on Linux/macOS (type "node-gyp rebuild" on the command line). It requires that the MS build tools are installed, though.

The tests ran through except for counter.js, which I just figured out is because a problem in the "release" function. Sorry about that!
I had assumed it gets passed an instance to a cache object, but it's only the name of the cache.
I just commented it out in this commit: https://github.com/matthias-christen/node-shared-cache/commit/49b683f640a419ed27a1d0bf64bc7fdf481bef61, but the clean up code should go somewhere where the object is destroyed/garbage collected (which doesn't seem to be so easy to do).

Another small oversight I noticed is that I used the wrong mutex name in one place, which I also fixed in the commit.

I'm not sure what to do about the clean up problem, but I could create another pull request if you like.

Thanks!

**Comment by kyriosli** [comment]
The function `release` means to release a shared memory block identified by the name, so it has nothing to do with gcs, no cache object shall be passed, because creating a cache object requires a `shm_open` operation, and a `mmap` operation, which is not necessary for an `release` operation, which only requires a `shm_unlink` operation.

Imagine that process `a` creates a cache object with name `blah`, and process `b` tries to free it. To accomplish the free operation, process `b` does not need to obtain a reference of the memory region, it only need the name of the shared file name.

Speaking of mswin, I figured out that the memory is automatically freed when all processes mapping the memory are dead. So the `release` should just **DO NOTHING** here.

By the way, I heard that `mutex` is something evil on windows, that could be really slow in comparison of `futex` on linux. could you post some performance data when `release` function has been fixed?

**Comment by matthias-christen** [comment]
The performance with the mutex synchronization on Windows doesn't seem too terrible (btw, on Mac (MBP 2012) the performance differences seem to be a lot larger).

Performance data on Win8.1, Intel i7-3615QM @ 2.3GHz:

```node .\test\benchmark.js```

```
write plain obj 100w times: 177.22ms
write shared cache 100w times: 554.55ms
read plain obj 100w times: 105.66ms
read shared cache 100w times: 565.28ms
read plain obj with key absent 100w times: 184.78ms
read shared cache with key absent 100w times: 599.59ms
enumerate plain obj 10w times: 760.49ms
enumerate shared cache 10w times: 2748.11ms
JSON.stringify 10w times: 13298.51ms
binary serialization 10w times: 4494.69ms
JSON.parse 10w times: 4921.94ms
binary unserialization 10w times: 2773.81ms
```

**Pull request merged**
